# Configuration for RoonFileTagger

# Directory settings
scan_directories_file: "config/scan_directories.txt"  # File containing list of directories to scan

# File patterns to scan
audio_file_patterns:
  - "*.mp3"
  - "*.flac"
  - "*.m4a"
  - "*.wav"

# Name correction file location
name_correction_file: "config/name_corrections.txt"

# API settings
theaudiodb:
  api_key: "2"  # Default test API key
  base_url: "https://www.theaudiodb.com/api/v1/json"

# Logging settings
logging:
  level: "INFO"
  file: "logs/roon_tagger.log" 